lib/theater_web/router.ex
defmodule TheaterWeb.Router do
  use TheaterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TheaterWeb do
    pipe_through :browser

    # get "/", PageController, :index
    get "/about", PageController, :about
    resources "/movies", MovieController
    resources "/actors", ActorController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TheaterWeb do
  #   pipe_through :api
  # end
end

lib/theater_web/views/layout_view.ex
defmodule TheaterWeb.LayoutView do
  use TheaterWeb, :view
end

lib/theater_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Theater · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "All movies", to: Routes.movie_path(@conn, :index) %></li>
            <li><%= link "All actors", to: Routes.actor_path(@conn, :index) %></li>
            <li><%= link "About", to: Routes.page_path(@conn, :about) %></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>